/* Lease Lane — pictogrammes bicolores.
   386 icônes extraites des 12 planches fournies par le client (uploads/), fond retiré par démélange des deux encres
   puis recoloriées aux couleurs de la marque : encre principale marine-900, accent bleu-500.
   Fichiers :
   · assets/icons/pictos/<jeu>/<nom>.webp — masque double 512×256 : moitié gauche = encre principale,
     moitié droite = accent. Le composant Icon les colore en CSS (currentColor + accent), à toutes les tailles.
   · assets/icons/pictos-couleur/<jeu>/<nom>.webp — version colorée 256×256 sur fond transparent,
     pour les courriels, documents et présentations.
   Identifiant : '<jeu>.<nom>' (ex. 'property.key'). Les noms suivent les libellés anglais des planches.
   Ils ne remplacent aucune icône d'interface : on les appelle explicitement, <Icon name="property.key" />. */
export const PICTO_JEUX = [
  {id:'property',nom:'Immobilier',icones:'rules property-search property-management community tenant-communication online-portal online-management rent-collection cctv parking property-alerts property-manager virtual-tour partnership rent-statement facility-management online-payment move-in key invoice property-documents feedback location property-dashboard insurance building-management repair notice real-estate-management automation smart-property commission contract mortgage property-manage owner'.split(' ')},
  {id:'finance',nom:'États financiers',icones:'balance-sheet income-statement cash-flow financial-analysis budget-planning expense-report profit-margin revenue-forecast asset-allocation liabilities-assessment equity-analysis financial-reporting investment-portfolio cash-management financial-ratios debt-management income-projection expense-tracking revenue-generation asset-management liability-management equity-allocation budget-management cash-flow-analysis profit-maximization revenue-recognition expense-control asset-evaluation liability-reduction equity-growth'.split(' ')},
  {id:'wealth',nom:'Patrimoine',icones:'personal-budget tax-optimization mortgage-loan bonds-allocation wealth-dashboard emergency-fund risk-assessment asset-allocation estate-planning portfolio-diversification net-worth-growth retirement-plan real-estate-property stocks-growth financial-planning fixed-deposit etf-investment wealth-advisor credit-score-report mutual-funds wealth-transfer investment-return financial-goal-target investment-strategy'.split(' ')},
  {id:'time',nom:'Temps',icones:'time fast-timer daily-schedule coffee-break running-time time-settings target-time stopwatch checklist future deadline fast-timer-stopwatch full-time time-search fast-work employee-time productivity work-time laptop-time clock 24-hours efficiency quick-response business-time planning time-support wrist-watch global-time time-management timer reminder rocket-launch alarm-clock refresh-time direction time-cycle meeting-time time-save calendar error'.split(' ')},
  {id:'project',nom:'Projets',icones:'project implementation integration strategy workflow budget plan task solution manager optimisation deadline manage to-do-list project-management meeting idea time-management schedule analytics collaboration goal-setting development decision'.split(' ')},
  {id:'productivity',nom:'Productivité',icones:'to-do-list task-management time-management productivity-tools calendar-scheduling goal-setting organization-tips focus-mode project-management deadline-tracker daily-planner efficiency-icon task-prioritization work-timer progress-bar productivity work-life-balance team-collaboration meeting-agenda task-delegation work-optimization time-blocking daily-checklist multitasking productivity-hacks work-efficiency milestone-tracker performance-metrics task-completion focused-work'.split(' ')},
  {id:'corporate',nom:'Entreprise',icones:'training deadline process-optimization communication growth optimization analytics workflow dashboard manager timer full-time business-report efficiency performance thinking calendar operational-excellence presentation teamwork target goal-setting project-management leadership achievement learning innovation smart-reminder productivity planning strategy corporate time-management time-save corporate-productivity organization milestone task-management automation success'.split(' ')},
  {id:'transformation',nom:'Transformation',icones:'business automation transformation-roadmap smart-business management leadership cloud-computing transformation analytics crisis dashboard data-analytics disruption customer-experience business-intelligence digitalization performance innovation growth modernization communication compliance technology-upgrade artificial-intelligence change-management enterprise-solution risk efficiency digital-strategy business-transformation governance business-model investment process-improvement restructuring customer'.split(' ')},
  {id:'continuity',nom:'Continuité des affaires',icones:'decision emergency crisis-planning disaster-recovery system-monitoring communication planning crisis-management crisis threat resilience industry-risk-control incident-response maintenance restoration business-continuity-plan disruption risk quality compliance response data-protection policy impact-analysis digital-industry acceptability alert audit data-backup corporate-support growth-down stakeholder down-time risk-assessment protection strategy'.split(' ')},
  {id:'reputation',nom:'Réputation',icones:'brand-reputation online-reviews reputation-score crisis-management public-relations customer-feedback social-media-monitoring review-response reputation-audit negative-review-handling media-coverage brand-image reputation-monitoring reputation-repair stakeholder-communication customer-satisfaction influencer-endorsement online-presence trust-building damage-control brand-perception customer-loyalty reputation-analytics corporate-image reputation-risk reputation-strategy positive-review public-opinion crisis-communication reputation-enhancement'.split(' ')},
  {id:'assets',nom:'Actifs numériques',icones:'digital-library asset-repository media-management file-organization tagging-system search-functionality asset-vault metadata-management cloud-storage group-library user-access-control digital-archive asset-sharing document-workflow asset-tagging collaboration-tools upload-and-download content-editing asset-analytics brand-assets video-library audio-files project-folders asset-backup rights-management digital-vault file-compression import-and-export asset-tracking asset-lifecycle-management'.split(' ')},
  {id:'inventory',nom:'Inventaire',icones:'stock-control warehouse-management inventory-tracking replenishment demand-forecasting stock-reordering supply-chain inventory-optimization shelf-stocking inventory-levels stock-rotation inventory-valuation just-in-time inventory-accuracy inventory-turnover add-product safety-stock dead-stock stock-monitoring inventory-reporting stock-audit fifo-lifo stock-reconciliation order-fulfillment stock-control-software stock-allocation stock-valuation multi-location-inventory serialized-inventory excess-inventory'.split(' ')}
];
