/* Généré depuis ui_kits/site-public/langue.js par scripts/conversion/convertir-langue.py — modifier la source.
   Chaque page française a sa jumelle anglaise : [chemin français, chemin anglais, titre, description, requête cible, libellé du fil d'Ariane]. */
var Q=[['limoilou','Limoilou'],['montcalm','Montcalm'],['saint-roch','Saint-Roch'],['saint-sauveur','Saint-Sauveur'],['sainte-foy','Sainte-Foy'],['charlesbourg','Charlesbourg'],['beauport','Beauport'],['lebourgneuf','Lebourgneuf'],['vieux-quebec','Old Québec']];
  var T=[
    ['/','/en','Property Management in Québec City | Lease Lane','Lease Lane manages your rental units in Québec City: fast leasing, rent collected, maintenance tracked and clear reporting. Cléo answers 24/7.','property management Quebec City','Home'],
    ['/gestion-immobiliere','/en/property-management','Property Management Company in Québec City | Lease Lane','Rental property management in Québec City: leasing, rent collection, maintenance and online reports. You keep the important decisions.','property management company Quebec City','Property management'],
    ['/gestion-immobiliere/location','/en/property-management/leasing','Find Tenants Fast in Québec City | Lease Lane','Marketing, viewings booked by Cléo 24/7 and tenant screening compliant with Law 25. See what a vacant unit really costs you.','find tenants fast Quebec City','Leasing and marketing'],
    ['/expertise-et-strategie','/en/rental-property-strategy','Rental Property Strategy and Expertise | Lease Lane','Rents, occupancy, planned maintenance and compliance: we analyze your building, propose a written plan and measure the results every month.','rental property strategy Quebec','Expertise and strategy'],
    ['/changer-de-gestionnaire','/en/switch-property-managers','Switch Property Managers Without Risk | Lease Lane','Leave your current property manager in four steps: contract review, transfer of leases and files, notice to tenants, first report.','switch property manager Quebec City','Switch property managers'],
    ['/cleo','/en/cleo','AI Assistant for Property Management | Lease Lane','Cléo, Lease Lane’s AI agent, explains Québec housing law and the TAL (formerly the Régie du logement) 24/7, triages emergencies and books viewings.','AI assistant property management','Cléo'],
    ['/logements-a-louer','/en/apartments-for-rent','Apartments for Rent in Québec City | Lease Lane','Rental units in Québec City managed by Lease Lane: filter by area, rooms, rent and date, and book a viewing anytime with Cléo.','apartments for rent Quebec City','Apartments for rent'],
    ['/logements-a-louer/4-et-demi-renove-montcalm','/en/apartments-for-rent/renovated-4-and-a-half-montcalm','Renovated 4½ for Rent in Montcalm, Québec City | Lease Lane','Renovated 880 sq ft 4½ in Montcalm, $1,450 a month, available July 1. Book a viewing with Cléo or apply online.','4 1/2 for rent Montcalm Quebec','Renovated 4½, Montcalm'],
    ['/locataires','/en/tenants','24/7 Tenant Services | Lease Lane','24/7 emergencies, rental applications, administration and complaints; repairs, tracking, rent and lease in the tenant portal. Cléo answers anytime.','tenant services Quebec City','Tenant services'],
    ['/locataires/demande-de-location','/en/tenants/rental-application','Rental Application | Lease Lane','Submit your rental application online. No deposit required; we only ask for the information we need, with your consent.','apartment rental application Quebec','Rental application'],
    ['/locataires/commentaire-ou-plainte','/en/tenants/comment-or-complaint','Comment or Complaint | Lease Lane','Comment, complaint or administrative request: instant acknowledgement and a reply within the published timeframe.','property manager complaint','Comment or complaint'],
    ['/faq','/en/faq','Property Management and Rental FAQ | Lease Lane','Straight answers for owners and tenants: offer, contract, transition, leasing, repairs, rent and lease.','property management FAQ Quebec','FAQ'],
    ['/blogue','/en/blog','Québec City Property Management Blog | Lease Lane','Housing law, building management and Lease Lane news: articles written by our team, reviewed and dated, with their sources.','property management blog Quebec City','Blog and news'],
    ['/blogue/hausse-de-loyer-2026','/en/blog/rent-increase-2026','2026 Rent Increase in Québec: Deadlines and the TAL | Lease Lane','Notice deadlines, the TAL calculation and the options for tenants and landlords, with the Civil Code articles cited. Reviewed by a legal professional.','rent increase 2026 Quebec TAL','2026 rent increase'],
    ['/a-propos','/en/about','About Lease Lane, Rental Management in Québec City','Lease Lane brings together a management team and Cléo, a 24/7 AI agent trained in housing law, for units leased faster and management you can see.','Lease Lane rental management','About'],
    ['/nous-joindre','/en/contact','Contact Lease Lane | Property Management in Québec City','Phone, email, our office in Lévis or Cléo 24/7: owner or tenant, choose how to reach Lease Lane.','contact Lease Lane','Contact us'],
    ['/offre-de-service','/en/get-a-quote','Get a Property Management Quote | Lease Lane','Describe your building in two minutes: type, number of units, area. We reply with a written offer and a proposed meeting.','property management quote Quebec City','Get a quote'],
    ['/quartiers','/en/neighbourhoods','Québec City Neighbourhood Guides for Tenants | Lease Lane','Nine Québec City neighbourhood guides: borough, landmarks and rental units managed by Lease Lane, with viewings bookable anytime with Cléo.','Quebec City neighbourhoods to rent','Neighbourhood guides'],
    ['/glossaire-bail-residentiel','/en/residential-lease-glossary','Québec Residential Lease Glossary | Lease Lane','Régie du logement, rent increase, lease assignment, security deposit: everyday words and the matching Civil Code or TAL term, with the source.','Quebec residential lease glossary','Residential lease glossary'],
    ['/temoins','/en/cookies','Cookie Policy | Lease Lane','The cookies used on leaselane.ca, what they are for, how long they last and how to change your choices at any time.','cookie policy','Cookies'],
    ['/conditions-utilisation','/en/terms-of-use','Terms of Use | Lease Lane','The terms that govern the use of leaselane.ca, Cléo, rental listings and online forms.','terms of use','Terms of use'],
    ['/confidentialite','/en/privacy-policy','Privacy Policy | Lease Lane','How Lease Lane collects, uses, keeps and protects your personal information, in accordance with Québec’s Law 25.','privacy policy Law 25','Privacy policy'],
    ['/gouvernance','/en/privacy-governance','Personal Information Governance | Lease Lane','Our person in charge of personal information protection, roles, the information life cycle, incidents and complaints (Law 25).','personal information governance Law 25','Personal information governance']
  ].concat(Q.map(function(q){var n=q[1];return ['/quartiers/'+q[0],'/en/neighbourhoods/'+q[0],'Apartments for Rent in '+n+', Québec City | Lease Lane',
    n+' neighbourhood guide for tenants: borough, landmarks and rental units managed by Lease Lane. Book a viewing 24/7 with Cléo.','apartment for rent '+n+' Quebec City',n]}));

export const ROUTES_EN = {};
export const FR_DE_EN = {};
T.forEach(function (t) { ROUTES_EN[t[0]] = {en: t[1], titre: t[2], description: t[3], requete: t[4], fil: t[5]}; FR_DE_EN[t[1]] = t[0]; });
const norm = function (p) { p = String(p || '/').split('?')[0]; return p.replace(/\/+$/, '') || '/'; };
/* Chemin anglais d'un chemin français (garde l'ancre); inconnu : /en + chemin. */
export function versEN(p) { const a = String(p || '/').split('#'), b = norm(a[0]), e = ROUTES_EN[b]; const r = e ? e.en : (b === '/' ? '/en' : '/en' + b); return a[1] ? r + '#' + a[1] : r; }
/* Chemin français d'un chemin anglais. */
export function versFR(p) { const a = String(p || '/').split('#'), b = norm(a[0]); const r = FR_DE_EN[b] || (b.indexOf('/en/') === 0 ? b.slice(3) : b === '/en' ? '/' : b); return a[1] ? r + '#' + a[1] : r; }
export const estEN = function (p) { return /^\/en(\/|$)/.test(p || ''); };
